A	.dockerignore
M	.gitignore
A	Dockerfile
D	chains/README.md
A	docker-compose.yml
A	econoeasy/__init__.py
A	econoeasy/app/__init__.py
A	econoeasy/app/core/__init__.py
A	econoeasy/app/core/config.py
A	econoeasy/app/main.py
A	econoeasy/app/models/__init__.py
A	econoeasy/app/models/schemas.py
A	econoeasy/app/routers/__init__.py
A	econoeasy/app/routers/summarize.py
A	econoeasy/app/services/__init__.py
A	econoeasy/app/services/queue/__init__.py
A	econoeasy/app/services/queue/mongodb_client.py
A	econoeasy/app/services/queue/redis_consumer.py
A	econoeasy/app/services/queue/worker.py
A	econoeasy/app/services/summarizer/__init__.py
A	econoeasy/app/services/summarizer/client.py
A	econoeasy/app/services/summarizer/parser.py
A	econoeasy/app/services/summarizer/prompts.py
A	econoeasy/app/services/summarizer/service.py
A	econoeasy/requirements.txt
D	models/README.md
D	prompts/README.md
D	requirements.txt
A	run_worker.sh
D	server.py
D	utils/README.md
